name: First Github Action

on: push

jobs:
    first-job: 
        runs-on : ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v2
          
        - name: Multiline commands 
          run: |
           echo " Welcome Captain My first Github Action Job"
           ls
           cat README.md

        