name: Generate ASCII Artwork 

on: push

jobs:
    ascii-job: 
        runs-on : ubuntu-latest
        steps:
        - name: Check out code
          uses: actions/checkout@v4

        - name: Execute Shell script
          run: ls -ltra

          
        - name: Execute Shell script
          run: |
            chmod +x ascii-script.sh
            ./ascii-script.sh

    