name: v1- Sync Release with Main 

on:
  workflow_dispatch:
    inputs:
      sync_repo:
        description: 'Select Repository'
        required: true
        type: choice
        options:
          - 'Github-Actions-Learning'
          - 'Test-GH'
          - 'modelmesh'
          - 'caikit-tgis-serving'
          - 'openvino'
          - 'vllm'
          - 'caikit-nlp'
          - 'caikit'
          - 'odh-model-controller'
          - 'caikit-tgis-backend'
          - 'caikit-nlp-client'
          - 'model-registry'
      main_branch:
        description: 'branch to pull from [main]'
        default: 'main'
        required: true
      release_branch:
        description: 'Branch to push to [release branch]'
        required: true

permissions:
  contents: write
  packages: write
  pull-requests: write

env:
  ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}
  

jobs:
  sync-and-pr:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git
        run: |
            git config --global user.name 'github-actions'
            git config --global user.email 'github-actions@github.com'

      - name: Checkout code
        uses: actions/checkout@v4
        with:
            repository: Raghul-M/${{ github.event.inputs.sync_repo }}
            token: ${{ secrets.ACTIONS_PAT }}
            fetch-depth: 0 # Let's get all the branches

      - name: Check the branches
        run: git branch -a
        
      - name: Merge Main to Release branch
        uses: devvspaces/merge-branches@v1
        with:
          token: ${{ github.token }}
          from_branch: ${{ github.event.inputs.main_branch }}
          to_branch:  ${{ github.event.inputs.release_branch }}
      
      - name: Create Pull Request to apply the sync merges
        run: |
          gh pr create --repo Raghul-M/${{ github.event.inputs.sync_repo }} \
          --head ${{ github.event.inputs.main_branch }}  \
          --base ${{ github.event.inputs.release_branch }} \
          --title "Main to RElease branch merge commits" \
          --body "$(echo -e "This is an automated PR created by GitHub Actions from the branch ${{ github.event.inputs.release_branch }}")"
      



      