name: Sync Release Branch with Main and Create PR

on:
  workflow_dispatch:
    inputs:
      sync_repo:
        description: 'Select Repository'
        required: true
        type: choice
        options:
          - 'Github-Actions-Learning'
          - 'Test-GH'
          - 'modelmesh'
          - 'caikit-tgis-serving'
          - 'openvino'
          - 'vllm'
          - 'caikit-nlp'
          - 'caikit'
          - 'odh-model-controller'
          - 'caikit-tgis-backend'
          - 'caikit-nlp-client'
          - 'model-registry'
      main_branch:
        description: 'Main branch to pull from'
        default: 'main'
        required: true
      release_branch:
        description: 'Branch to push to [release branch]'
        required: true

env:
  ACTIONS_PAT: ${{ secrets.ACTIONS_PAT }}

jobs:
  sync-branches:
    runs-on: ubuntu-latest
    name: Sync Release Branch with Main
    steps:
      - name: Configure Git
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "github-actions@github.com"

      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          repository: Raghul-M/${{ github.event.inputs.sync_repo }}
          token: ${{ secrets.ACTIONS_PAT }}
          fetch-depth: 0
          
      - name: Fetch all branches
        run: git fetch --all

      - name: Update remote tracking information
        run: git remote update origin

      - name: Merge release into main
        run: |
          git checkout ${{ github.event.inputs.main_branch }}
          git pull --rebase origin ${{ github.event.inputs.main_branch }}
          git merge --no-ff ${{ github.event.inputs.release_branch }}
          git commit -m "Automate Sync main with release" || echo "No changes to commit"
          git push origin ${{ github.event.inputs.main_branch }}
